export type RoastIntensity = string;
export type LearningLanguage = string;
export type SpecialistCategory = 'CODING' | 'UI_UX' | 'ARCHITECTURE_REASONING' | 'DEBUGGING_TESTING' | 'FAST_SIMPLE' | 'GENERAL' | 'VISION' | 'VOICE';
export interface TopicAssessment { attempts: number; successes: number; failures: number; accuracy: number; mastery: number; lastAttemptAt?: string; [key: string]: any; }
export interface Recommendation { action: string; reason: string; evidence?: string; priority: 'HIGH' | 'MEDIUM' | 'LOW'; }
export interface ModelCapability { id: string; name: string; provider: string; category: SpecialistCategory; contextWindow?: number; maxTokens?: number; supportsStreaming?: boolean; supportsVision?: boolean; costTier: 'FREE' | 'LOW' | 'MEDIUM' | 'HIGH'; healthy: boolean; latencyMs?: number; failureCount: number; cooldownUntil?: number; }
export interface AIRoutingRecord { requestId: string; timestamp: string; category: SpecialistCategory; selectedProvider: string; selectedModel: string; fallbackChain: string[]; latencyMs: number; success: boolean; errorReason?: string; promptTokens?: number; completionTokens?: number; }
export interface IncidentLog { id: string; timestamp: string; errorType: string; errorMessage: string; codeSnippet: string; lessonId: string; roastMessage: string; persona: string; repeatCount: number; levelTitle?: string; status?: string; }
export interface EvaluationResult { passed: boolean; userOutput: string; errorType?: string; errorMessage?: string; roastMessage: string; explanation: string; fixHint: string; personaUsed: string; }
export interface UserProgress { id?: string; userId?: string; xp: number; streak: number; level: number; currentLessonId: string; currentChallengeIndex: number; completedLessons: string[]; masteredTopics: string[]; weakTopics: string[]; roastIntensity: string; learningLanguage: string; diagnosticCompleted: boolean; incidents: IncidentLog[]; achievements: any[]; topicStats?: Record<string, TopicAssessment>; topicMastery?: Record<string, number>; topicAccuracy?: Record<string, number>; topicRetention?: Record<string, number>; topicIndependentSolve?: Record<string, number>; hintDependency?: Record<string, number>; confidenceIndicators?: Record<string, number>; lastActiveTimestamp?: string; interviewReadiness: number; recommendations?: unknown[]; routingLogs?: AIRoutingRecord[]; aiTutor: { totalSessions: number; totalHintsProvided: number; learningStyleProfile: 'VISUAL' | 'HANDS_ON' | 'THEORETICAL' | 'MIXED'; commonErrorPatterns: string[]; streakStatus: 'ACTIVE' | 'BREAK' | 'RENEWED'; lastInteractionAt: string; proficiencyScore: number; recommendedIntensity: string; }; behavioralPatterns: { dependencyDetected: boolean; excessiveHints: boolean; repeatedMistakePatterns: string[]; independentSuccessCount: number; assistedSuccessCount: number; lastIndependentAttempt: string; }; misconceptions: { tracked: string[]; lastDetected: string; detectionCount: number; }; }
